routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/items', function(){
    return view('items.desa.index');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index');
Route::get('/', 'DashboardController@index');

// Route::get('/', function () {
//     return view('index');
// });


Route::resource('desa', 'DesaController');
Route::resource('posting', 'PostingController');
Route::resource('profiles', 'ProfilesController');
Route::resource('penerima', 'PenerimaController');
Route::resource('komentar', 'KomentarController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
    
});

Route::post('like', 'LikesController@like');
Route::delete('like', 'LikesController@dislike');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = [];

    
}

app/Http/Controllers/ProfilesController.php
<?php

namespace App\Http\Controllers;

use App\Profile;
use App\User;
use Illuminate\Http\Request;
use DB;
use Auth;

class ProfilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('auth');
        // $this->middleware('auth')->except(['index']);
        // $this->middleware('auth')->only(['create','edit','update','store','index']);
    }
    public function index()
    {
        // $profiles = Profiles::all();
        // dd($profiles->author);
        // $id = Auth::id();
        // $user = Auth::user();
        // $cek = Profile::where('user_id', $id)->get();
        // $cek = Profile::firstOrCreate(['user_id' => $id]);
        // dd($user);
        
        // $ceks = Profile::where('user_id', '2')->get();
        // dd($ceks);
        // $profile_id = Auth::user()->profiles->fullname;
        // $profile_id = Auth::user()->profiles;
        $dataprofil = Auth::user()->dataprofil->id;
        $profiles = Profile::find($dataprofil);
        
        return view('items.profiles.index', compact('profiles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fullname' => 'required',
            'phone' => 'required'
        ]);
            // dd($request);
        $profiles = Profiles::create([
            "fullname" => $request["fullname"],
            "phone" => $request["phone"],
            "photo" => "foto.jpg",
            "users_id" => Auth::id()
        ]);

        // $user = Auth::user();
        // $user->profiles()->save($profiles);

        return redirect('/profiles')->with('success', 'Profil Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Profiles  $profiles
     * @return \Illuminate\Http\Response
     */
    public function show(Profiles $profiles)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Profiles  $profiles
     * @return \Illuminate\Http\Response
     */
    public function edit(Profiles $profiles)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Profiles  $profiles
     * @return \Illuminate\Http\Response
     */
    public function update($profiles, Request $request){
    
        
        // dd($request->all());    
            
        $update = Profile::where('id', $profiles)->update([
            "full_name" => $request["full_name"],
            "phone" => $request["phone"]
        ]);
        if($request->hasFile('photo')){
            $request->file('photo')->move('img',$request->file('photo')->getClientOriginalName());
            $update = Profile::where('id', $profiles)->update([
                "photo" => $request->file('photo')->getClientOriginalName()
            ]);
        }

        return redirect('/profiles')->with('success', 'Task Created Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Profiles  $profiles
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profiles $profiles)
    {
        //
    }
}

resources/views/items/profiles/index.blade.php
@extends('adminLTE.master')

@section('content')
<div class="ml-3 mt-3">
    <div class="card card-primary">
      {{-- @if (session('success'))
                    <div class="alert alert-success">
                        {{session('success')}}
                    </div>
                @endif   --}}
      <div class="card-header">
        <h3 class="card-title">Edit Data Profil</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form role="form" action="{{ route('profiles.update', ['profile' => $profiles->id])}}" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Full Name</label>
                <?php 
                  if($profiles->full_name == NULL){
                    $fullname = Auth::user()->name;
                  }else{
                    $fullname = $profiles->full_name;
                  }; 
                ?>
                <input type="text" name="full_name" value="{{old('full_name',$fullname)}}" class="form-control" id="exampleInputPassword1" placeholder="Masukan Nama Lengkap">
                @error('full_name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror  
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Nomor HP</label>
                <input type="text" name="phone" value="{{old('phone',$profiles->phone)}}" class="form-control" id="exampleInputPassword1" placeholder="Masukan Nomor HP">
                @error('phone')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror  
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Foto Profil</label>
              <input type="file" name="photo" class="form-control" placeholder="Upload Foto Profil">
              @error('phone')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror  
          </div>
        </div>
        
      </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Update Data</button>
        </div>
      </form>
    </div>
  </div>
@endsection

@push('script')
@include('sweetalert::alert')
@endpush