routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/items', function(){
    return view('items.desa.index');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index');
Route::get('/', 'DashboardController@index');

// Route::get('/', function () {
//     return view('index');
// });


Route::resource('desa', 'DesaController');
Route::resource('posting', 'PostingController');
Route::resource('profiles', 'ProfilesController');
Route::resource('penerima', 'PenerimaController');
Route::resource('komentar', 'KomentarController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
    
});

Route::post('like', 'LikesController@like');
Route::delete('like', 'LikesController@dislike');

app/Penerima.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Penerima extends Model
{
    protected $table = 'penerima';
    protected $guarded = [];

    public function ambildataprovinsi(){
        return $this->belongsTo('App\Provinsi', 'provinsi_id');
    }
    public function ambildatakabupaten(){
        return $this->belongsTo('App\Kabupaten', 'kab_kota_id');
    }
    public function ambildatakecamatan(){
        return $this->belongsTo('App\Kecamatan', 'kecamatan_id');
    }
    public function ambildatadesa(){
        return $this->belongsTo('App\Desa', 'desa_kel_id');
    }
    public function ambildatabantuan(){
        return $this->belongsTo('App\Bantuan', 'jenis_bantuan_id');
    }

}

app/Http/Controllers/PenerimaController.php
<?php

namespace App\Http\Controllers;

use App\Penerima;
use App\Provinsi;
use App\Kabupaten;
use App\Kecamatan;
use App\Desa;
use App\Bantuan;
use App\User;
use Illuminate\Http\Request;
use DB;
use Auth;

class PenerimaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('auth');
        // $this->middleware('auth')->except(['index']);
        // $this->middleware('auth')->only(['create','edit','update','store','index']);
    }

    public function index()
    {
        $penerima   = Penerima::all();
        $provinsi   = Provinsi::all();
        $kabupaten  = Kabupaten::all();
        $kecamatan  = Kecamatan::all();
        $desa       = Desa::all();
        $bantuan    = Bantuan::all();
        // dd($penerima->ambildatakabupaten);
        //$bantuan    = bantuan::with(['penerima','penerima.jenis_bantuan_id'])->get();
        return view('items.penerima.index', compact('penerima','provinsi','kabupaten','kecamatan','desa','bantuan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $provinsi      = Provinsi::all();
        $kabupaten     = Kabupaten::all();
        $kecamatan     = Kecamatan::all();        
        $desa          = Desa::all();
        $bantuan       = Bantuan::all();
        return view('items.penerima.create', compact('provinsi','kabupaten','kecamatan','desa','bantuan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'no_ktp'       => 'required',
            'nama_lengkap' => 'required'
        ]);
            // dd($request);
       
        $penerima  = Penerima::create([
            "no_ktp"            => $request["no_ktp"],
            "alamat"            => $request["alamat"], 
            "jenis_bantuan_id"  => $request["bantuan"],
            "desa_kel_id"       => $request["desa"],
            "kecamatan_id"      => $request["kecamatan"],
            "kab_kota_id"       => $request["kabupaten"],
            "nama_lengkap"      => $request["nama_lengkap"],
            "provinsi_id"       => $request["provinsi"],
            "users_id" => Auth::id()
        ]);

        return redirect('/penerima')->with('success', 'Penerima Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Penerima  $penerima
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $penerima = Penerima::find($id)->first();
        //dd($pertanyaan->author);
        // $penerima   = Penerima::all()->first();
        // $provinsi   = Provinsi::all();
        // $kabupaten  = Kabupaten::all();
        // $kecamatan  = Kecamatan::all();
        // $desa       = Desa::all();
        // $bantuan    = Bantuan::all();
        // dd($penerima->ambildataprovinsi);
        return view('items.penerima.show', compact('penerima'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Penerima  $penerima
     * @return \Illuminate\Http\Response
     */
    public function edit($penerima)
    {   
        $penerima = Penerima::find($penerima);
        $provinsi      = Provinsi::all();
        $kabupaten     = Kabupaten::all();
        $kecamatan     = Kecamatan::all();        
        $desa          = Desa::all();
        $bantuan       = Bantuan::all();
        return view('items.penerima.edit', compact('penerima','provinsi','kabupaten','kecamatan','desa','bantuan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Penerima  $penerima
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $penerima)
    {
        $request->validate([
            'no_ktp'       => 'required',
            'nama_lengkap' => 'required',
            'bantuan' => 'required',
            'desa' => 'required',
            'kecamatan' => 'required',
            'kabupaten' => 'required',
            'alamat' => 'required',
            'provinsi' => 'required'
        ]);
            // dd($request);
       
        $penerima  = Penerima::where('id', $penerima)->update([
            "no_ktp"            => $request["no_ktp"],
            "alamat"            => $request["alamat"], 
            "jenis_bantuan_id"  => $request["bantuan"],
            "desa_kel_id"       => $request["desa"],
            "kecamatan_id"      => $request["kecamatan"],
            "kab_kota_id"       => $request["kabupaten"],
            "nama_lengkap"      => $request["nama_lengkap"],
            "provinsi_id"       => $request["provinsi"]
        ]);


        return redirect('/penerima')->with('success', 'Penerima berhasil diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Penerima  $penerima
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Penerima::destroy($id);
        return redirect('/penerima')->with('success', 'Penerima Berhasil dihapus');
    }
}

resources/views/items/penerima/create.blade.php
@extends('adminLTE.master')

@section('content')

<div class="ml-3 mt-3">
    <!-- general form elements -->
    <div class="card card-primary">
      @if (session('success'))
                  <div class="alert alert-success">
                      {{session('success')}}
                  </div>
              @endif  
      <div class="card-header">
        <h3 class="card-title">Tambah Penerima</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form role="form" action="{{ route('penerima.store')}}" method="POST">
        @csrf
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Nomor KTP</label>
            <input type="text" class="form-control" name="no_ktp" id="no_ktp" placeholder="Nomor KTP">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Nama Lengkap</label>
            <input type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" placeholder="Nama Lengkap">
          </div>
         
          <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <select name="provinsi" id="provinsi" class="form-control select2" style="width: 100%;">
              <option selected="selected">Provinsi</option>
              @foreach ($provinsi as $id => $myProvinsi)
                  <option value="{{$myProvinsi->id}}">{{$myProvinsi->nama_provinsi}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kabupaten Kota</label>
            <select name="kabupaten" id="kabupaten" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Kabupaten / Kota</option>
              @foreach ($kabupaten as $id => $myKabupaten)
                  <option value="{{$myKabupaten->id}}">{{$myKabupaten->nama_kabKota}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kecamatan</label>
            <select name="kecamatan" id="kecamatan" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Kecamatan</option>
              @foreach ($kecamatan as $id => $mykecamatan)
                  <option value="{{$mykecamatan->id}}">{{$mykecamatan->nama_kecamatan}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Desa / Kelurahan</label>
            <select name="desa" id="desa" class="form-control select2" style="width: 100%;">
              <option selected="selected">PIlih Desa / Kelurahan</option>
              @foreach ($desa as $id => $myDesa)
                  <option value="{{$myDesa->id}}">{{$myDesa->nama_desaKel}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Alamat</label>
            <textarea class="form-control" name="alamat" id="alamat" cols="20" rows="5"></textarea>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Jenis Bantuan</label>
            <select name="bantuan" id="bantuan" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Jenis Bantuan</option>
              @foreach ($bantuan as $id => $myBantuan)
                  <option value="{{$myBantuan->id}}">{{$myBantuan->nama_bantuan}}</option>
              @endforeach
            </select>
          </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <!-- /.card -->

  </div>
  <!--/.col (left) -->
@endsection

@push('stack')
<!-- Select2 -->
<script src="{{ asset ('/adminLTE/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset ('/adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
  
      //Initialize Select2 Elements
      $('.select2bs4').select2({
        theme: 'bootstrap4'
      })
    })
</script>
@endpush

resources/views/items/penerima/edit.blade.php
@extends('adminLTE.master')

@section('content')

<div class="ml-3 mt-3">
    <!-- general form elements -->
    <div class="card card-primary">
      @if (session('success'))
                  <div class="alert alert-success">
                      {{session('success')}}
                  </div>
              @endif  
      <div class="card-header">
        <h3 class="card-title">Tambah Penerima</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form role="form" action="{{ route('penerima.update', ['penerima' => $penerima->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Nomor KTP</label>
            <input required type="text" value="{{old('no_ktp',$penerima->no_ktp)}}"  class="form-control" name="no_ktp" id="no_ktp" placeholder="Nomor KTP">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Nama Lengkap</label>
            <input required type="text" value="{{old('no_ktp',$penerima->nama_lengkap)}}" class="form-control" name="nama_lengkap" id="nama_lengkap" placeholder="Nama Lengkap">
          </div>
         
          <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <select required name="provinsi" id="provinsi" class="form-control select2" style="width: 100%;">
              <option selected="selected">Provinsi</option>
              @foreach ($provinsi as $id => $myProvinsi)
                  <option value="{{$myProvinsi->id}}">{{$myProvinsi->nama_provinsi}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kabupaten Kota</label>
            <select required name="kabupaten" id="kabupaten" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Kabupaten / Kota</option>
              @foreach ($kabupaten as $id => $myKabupaten)
                  <option value="{{$myKabupaten->id}}">{{$myKabupaten->nama_kabKota}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kecamatan</label>
            <select required name="kecamatan" id="kecamatan" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Kecamatan</option>
              @foreach ($kecamatan as $id => $mykecamatan)
                  <option value="{{$mykecamatan->id}}">{{$mykecamatan->nama_kecamatan}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Desa / Kelurahan</label>
            <select required name="desa" id="desa" class="form-control select2" style="width: 100%;">
              <option selected="selected">PIlih Desa / Kelurahan</option>
              @foreach ($desa as $id => $myDesa)
                  <option value="{{$myDesa->id}}">{{$myDesa->nama_desaKel}}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Alamat</label>
            <textarea required class="form-control" name="alamat" id="alamat" cols="20" rows="5">{{$penerima->alamat}}</textarea>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Jenis Bantuan</label>
            <select required name="bantuan" id="bantuan" class="form-control select2" style="width: 100%;">
              <option selected="selected">Pilih Jenis Bantuan</option>
              @foreach ($bantuan as $id => $myBantuan)
                  <option value="{{$myBantuan->id}}">{{$myBantuan->nama_bantuan}}</option>
              @endforeach
            </select>
          </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <!-- /.card -->

  </div>
  <!--/.col (left) -->
@endsection

@push('stack')
<!-- Select2 -->
<script src="{{ asset ('/adminLTE/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset ('/adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
  
      //Initialize Select2 Elements
      $('.select2bs4').select2({
        theme: 'bootstrap4'
      })
    })
</script>
@endpush

resources/views/items/penerima/index.blade.php
@extends('adminLTE.master')

@section('content')
    <div class="mt-2 ml-3">
        <div class="card-header">
            <h3 class="card-title">Data Penerima</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success')}}
                </div>
            @endif
            <a href="/penerima/create" class="btn btn-primary mb-2">Tambah</a>
            <table class="table table-bordered">
              <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nomor KTP</th>
                    <th scope="col">Nama Lengkap</th>
                    <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse($penerima as $key => $value)
                <tr>
                    <td>{{$key + 1}}</th>
                    <td>{{$value->no_ktp}}</td>
                    <td>{{$value->nama_lengkap}}</td>
                    <td style="display:flex">
                        <a href="/penerima/{{$value->id}}" class="btn btn-info btn-sm">Show</a>&nbsp;
                        <a href="/penerima/{{$value->id}}/edit" class="btn btn-primary btn-sm">Edit</a>&nbsp;
                        <form action="/penerima/{{$value->id}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="delete" class="btn btn-danger btn-sm">
                        </form>
                    </td>
                </tr>
                @empty
                    <tr colspan="3">
                        <td colspan="8" align="center">No data</td>
                    </tr>  
                @endforelse
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
    </div>
@endsection

@push('script')
@include('sweetalert::alert')

@endpush

resources/views/items/penerima/show.blade.php
@extends('adminLTE.master')

@section('content')

<div class="ml-3 mt-3">
    <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Penerima</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Nomor KTP</label>
            <input readonly type="text" class="form-control" name="no_ktp" id="no_ktp" value="{{$penerima->no_ktp}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Nama Lengkap</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->nama_lengkap}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->ambildataprovinsi->nama_provinsi}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kabupaten</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->ambildatakabupaten->nama_kabKota}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Kecamatan</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->ambildatakecamatan->nama_kecamatan}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Desa</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->ambildatadesa->nama_desaKel}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Alamat</label>
            <textarea readonly class="form-control" name="alamat" id="alamat" cols="20" rows="5">{{$penerima->alamat}}</textarea>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Jenis Bantuan</label>
            <input readonly type="text" class="form-control" name="nama_lengkap" id="nama_lengkap" value="{{$penerima->ambildatabantuan->nama_bantuan}}">
          </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </div>
  <!--/.col (left) -->
@endsection