routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/items', function(){
    return view('items.desa.index');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index');
Route::get('/', 'DashboardController@index');

// Route::get('/', function () {
//     return view('index');
// });


Route::resource('desa', 'DesaController');
Route::resource('posting', 'PostingController');
Route::resource('profiles', 'ProfilesController');
Route::resource('penerima', 'PenerimaController');
Route::resource('komentar', 'KomentarController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
    
});

Route::post('like', 'LikesController@like');
Route::delete('like', 'LikesController@dislike');

app/Desa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Desa extends Model
{
    protected $table = 'desa_kel';
    protected $guarded = [];

}

app/Http/Controllers/DesaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Desa;
use Auth;
use DB;

class DesaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('auth');
        // $this->middleware('auth')->except(['index']);
        // $this->middleware('auth')->only(['create','edit','update','store','index']);
    }

    public function index()
    {
        $desa = Desa::all(); //klo menampilkan banyak data
        //dd($desa);
        return view('items.desa.index', compact('desa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('items.desa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
            'nama_desaKel' => 'required'
        ]);
        
        $desa = Desa::create([    
            "nama_desaKel" => $request["nama_desaKel"], 
        ]);
        //dd($desa);
        return redirect('/desa')->with('success', 'Tambah Desa/Kelurahan Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/items/desa/index.blade.php
@extends('adminLTE.master')

@section('content')

    <div class="card">
       @if (session('success'))
        <div class="alert alert-success">
            {{session('success')}}
        </div>
        @endif  
        <div class="card-header">
        <h3 class="card-title">DataTable with default features</h3>
        </div>
        <!-- /.card-header -->

        <div class="card-body">
        <button type="button" class="btn btn-secondary mb-2" data-toggle="modal" data-target="#modal-default">
            Tambah
        </button>
        <div class="modal fade" id="modal-default">
            <div class="modal-dialog">
            <form role="form" action="{{ route('desa.store')}}" method="POST">
              @csrf
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Tambah Desa</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Nama Desa / Kelurahan</label>
                      <input type="text" name="nama_desaKel" value="{{ old('nama_desaKel','')}}" class="form-control" id="nama_desaKel" placeholder="Nama Desa / Kelurahan">
                      @error('nama_desaKel')
                          <div class="alert alert-danger">{{ $message }}</div>
                      @enderror
                  </div>
                </div>
                <div class="modal-footer justify-content-between">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
              </div>
              <!-- /.modal-content -->
            </form>
            </div>
            <!-- /.modal-dialog -->
          </div>
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
            <th>#</th>
            <th>Kecamatan</th>
            <th>Nama Desa</th>
            <th>Created At</th>
            <th>Update At</th>
            <th>Action</th>
            </tr>
            </thead>
            <tbody>
              @foreach($desa as $key => $value)
              <tr>
                <td>{{$key + 1}}</th>
                <td>{{$value->kecamatan_id}}</td>
                <td>{{$value->nama_desaKel}}</td>
                <td>{{$value->created_at}}</td>
                <td>{{$value->updated_at}}</td>
                <td style="display:flex">
                  <a href="{{ route('desa.show', ['desa' => $value->id ]) }}" class="btn btn-info btn-sm">Show</a>
                  <a href="{{route('desa.edit', ['desa' => $value->id])}}">Edit</a>
                  <form action="{{ route('desa.destroy', ['desa' => $value->id])}}" method="POST">
                      @csrf
                      @method('DELETE')
                      <input type="submit" value="delete" class="btn btn-danger btn-sm">
                  </form>
                </td>
              </tr>

              @endforeach
            </tfoot>
        </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@endsection

@push('script')
    <!-- DataTables  & Plugins -->
    <script src="{{ asset ('/adminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/jszip/jszip.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/pdfmake/pdfmake.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/pdfmake/vfs_fonts.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{ asset ('/adminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js')}}"></script>
    <script>
    $(function () {
        $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
        });
    });
    </script>
@endpush